/* ============================================================
   KONTEN YAKESMA — dikelola lewat halaman admin (/admin/).
   File ini adalah "sumber kebenaran" isi situs. Jangan diedit
   manual kecuali paham strukturnya; gunakan admin lalu Terbitkan.
   ============================================================ */
window.YAKESMA_DATA = {
  site: {
    name: "YAKESMA",
    tagline: "Lembaga Amil Zakat Nasional",
    intro:
      "Ikuti kajian, kelas, webinar, dan program kebaikan YAKESMA. Perluas ilmu, perbanyak amal, raih keberkahan.",
    whatsapp: "6281234567890",
    email: "info@yakesma.org",
    instagram: "yakesma.official",
    website: "yakesma.org",
    address: "Jl. Contoh Alamat No. 1, Jakarta Selatan",
    bankName: "Bank Syariah Indonesia (BSI)",
    accountNumber: "1234567890",
    accountHolder: "Yayasan YAKESMA",
    logo: "yakesma-logo.png",
    mark: "yakesma-mark.png",
    colors: { green: "#28a840", dark: "#185838", gold: "#f6b700", orange: "#f58634" },
  },
  categories: ["Kajian", "Webinar", "Kelas", "Seminar", "Sosial", "Relawan", "Lari Virtual"],
  events: [
    {
      slug: "bali-international-virtual-run",
      title: "Bali International Virtual Run",
      category: "Lari Virtual",
      location: "Virtual (Lari di Mana Saja)",
      city: "Online",
      online: true,
      date: "2026-08-17",
      timeStart: "00:00",
      timeEnd: "23:59",
      price: 250000,
      quota: 1000,
      registered: 0,
      requiresShipping: true,
      gradient: ["#f58634", "#f6b700"],
      emoji: "🏃",
      excerpt:
        "Lari di mana saja, kapan saja, sepanjang 17 Agustus 2026 — rayakan kemerdekaan sambil berbagi kebaikan.",
      about: [
        "Bali International Virtual Run mengajak Anda berlari 5K, 10K, atau jarak pilihan Anda sendiri — di kota mana pun Anda berada — dalam rangka memperingati Hari Kemerdekaan RI sekaligus mendukung program kebaikan YAKESMA.",
        "Cukup daftar, lari kapan saja sepanjang 17 Agustus 2026, lalu dokumentasikan aktivitas Anda. Jersey eksklusif dan medali finisher akan dikirim langsung ke alamat Anda setelah event berakhir.",
      ],
      benefits: [
        "Jersey eksklusif Bali International Virtual Run",
        "Medali finisher",
        "E-sertifikat resmi",
        "Sebagian biaya pendaftaran disalurkan untuk program sosial YAKESMA",
      ],
      featured: true,
    },
    {
      slug: "kajian-akbar-keajaiban-sedekah",
      title: "Kajian Akbar: Keajaiban Sedekah",
      category: "Kajian",
      speaker: "Ustadz Ahmad Zaki, Lc.",
      location: "Masjid Raya Bintaro",
      city: "Jakarta",
      online: false,
      date: "2026-08-10",
      timeStart: "08:00",
      timeEnd: "11:00",
      price: 0,
      quota: 500,
      registered: 312,
      gradient: ["#28a840", "#185838"],
      emoji: "🕌",
      excerpt: "Menyelami keutamaan sedekah dan bagaimana ia membuka pintu rezeki.",
      about: [
        "Sedekah bukan mengurangi harta, melainkan mengundang keberkahan. Dalam kajian ini kita akan membahas dalil-dalil keutamaan sedekah serta kisah nyata bagaimana sedekah mengubah hidup seseorang.",
        "Terbuka untuk umum, gratis, dan disediakan snack untuk 500 peserta pertama. Mari hadir dan ajak keluarga.",
      ],
      benefits: ["Materi kajian & e-sertifikat kehadiran", "Snack dan minuman", "Kesempatan tanya-jawab langsung"],
      featured: true,
    },
    {
      slug: "morning-flow",
      title: "Morning Flow",
      category: "Sosial",
      speaker: "",
      location: "",
      city: "Online",
      online: true,
      date: "2026-07-29",
      timeStart: "",
      timeEnd: "",
      price: 1000,
      quota: 100,
      registered: 0,
      gradient: ["#f58634", "#f6b700"],
      emoji: "🌙",
      excerpt: "Sedekah rutin",
      about: ["Sedekah rutin!"],
      benefits: ["Laporan berkala dari sedekah harian"],
      featured: false,
    },
    {
      slug: "webinar-tunaikan-zakat-era-digital",
      title: "Webinar: Tunaikan Zakat di Era Digital",
      category: "Webinar",
      speaker: "Tim Edukasi YAKESMA",
      location: "Online (Zoom)",
      city: "Online",
      online: true,
      date: "2026-08-16",
      timeStart: "19:30",
      timeEnd: "21:00",
      price: 0,
      quota: 1000,
      registered: 648,
      gradient: ["#1f9036", "#0e6b4e"],
      emoji: "💻",
      excerpt: "Cara mudah menghitung dan menunaikan zakat secara online, anti ribet.",
      about: [
        "Zakat kini bisa ditunaikan hanya dari genggaman. Webinar ini mengupas jenis-jenis zakat, cara menghitung nisab, hingga praktik menunaikan zakat secara digital yang aman dan amanah.",
        "Cocok untuk Anda yang ingin memastikan zakatnya tepat hitung dan tepat sasaran.",
      ],
      benefits: ["Link Zoom & rekaman webinar", "Kalkulator zakat digital", "E-sertifikat peserta"],
      featured: true,
    },
    {
      slug: "kelas-tahsin-al-quran-intensif",
      title: "Kelas Tahsin Al-Qur'an Intensif (4 Pekan)",
      category: "Kelas",
      speaker: "Ustadzah Halimah, S.Pd.I.",
      location: "Online (Zoom)",
      city: "Online",
      online: true,
      date: "2026-08-23",
      timeStart: "09:00",
      timeEnd: "10:30",
      price: 150000,
      quota: 40,
      registered: 28,
      gradient: ["#f6b700", "#f58634"],
      emoji: "📖",
      excerpt: "Perbaiki bacaan Al-Qur'an dari makhraj hingga tajwid dalam 4 pekan.",
      about: [
        "Program intensif 4 pekan (8 pertemuan) untuk memperbaiki bacaan Al-Qur'an. Dibimbing langsung oleh pengajar bersanad dengan kelompok kecil agar setiap peserta mendapat koreksi personal.",
        "Kontribusi kelas digunakan untuk operasional pengajar dan program tahsin gratis bagi dhuafa.",
      ],
      benefits: ["8 sesi live via Zoom + rekaman", "Modul tahsin & lembar evaluasi", "Grup pendampingan dan e-sertifikat"],
    },
    {
      slug: "seminar-fikih-zakat-wakaf-kontemporer",
      title: "Seminar Fikih Zakat & Wakaf Kontemporer",
      category: "Seminar",
      speaker: "Dr. H. Abdurrahman, M.A.",
      location: "Hotel Grand Malabar",
      city: "Bandung",
      online: false,
      date: "2026-09-06",
      timeStart: "08:00",
      timeEnd: "15:00",
      price: 75000,
      quota: 200,
      registered: 96,
      gradient: ["#185838", "#28a840"],
      emoji: "🎓",
      excerpt: "Membahas isu-isu zakat & wakaf modern: saham, kripto, hingga wakaf uang.",
      about: [
        "Seminar sehari penuh membahas penerapan fikih zakat dan wakaf pada instrumen modern seperti zakat penghasilan, zakat saham, hingga wakaf uang dan wakaf produktif.",
        "Menghadirkan pemateri ahli dan sesi diskusi panel. Termasuk makan siang dan coffee break.",
      ],
      benefits: ["Seminar kit & makan siang", "Sertifikat resmi (SKP tersedia)", "Materi presentasi para pemateri"],
      featured: true,
    },
    {
      slug: "santunan-wisata-1000-anak-yatim",
      title: "Santunan & Wisata 1000 Anak Yatim",
      category: "Sosial",
      speaker: "",
      location: "Taman Impian Ceria",
      city: "Jakarta",
      online: false,
      date: "2026-09-14",
      timeStart: "07:00",
      timeEnd: "16:00",
      price: 100000,
      quota: 300,
      registered: 154,
      gradient: ["#f58634", "#f6b700"],
      emoji: "🎈",
      excerpt: "Berbagi kebahagiaan bersama 1000 anak yatim lewat santunan dan wisata.",
      about: [
        "Sehari penuh keceriaan bersama 1000 anak yatim: santunan, permainan edukatif, dan wisata bersama. Partisipasi Anda menjadi paket donasi untuk seorang anak yatim.",
        "Anda dapat hadir langsung sebagai kakak pendamping atau berdonasi tanpa hadir. Setiap kontribusi Rp100.000 menanggung satu anak.",
      ],
      benefits: ["Menanggung 1 paket santunan anak yatim", "Kaos relawan (jika hadir)", "Laporan & dokumentasi kegiatan"],
    },
    {
      slug: "relawan-distribusi-sembako-pelosok",
      title: "Relawan Distribusi Sembako Pelosok",
      category: "Relawan",
      speaker: "",
      location: "YAKESMA Center",
      city: "Jakarta",
      online: false,
      date: "2026-08-30",
      timeStart: "06:00",
      timeEnd: "selesai",
      price: 0,
      quota: 60,
      registered: 41,
      gradient: ["#28a840", "#1f9036"],
      emoji: "🤝",
      excerpt: "Jadi relawan pengemasan dan distribusi sembako untuk keluarga prasejahtera.",
      about: [
        "Kami membuka pendaftaran relawan untuk membantu pengemasan dan penyaluran paket sembako ke wilayah pelosok. Tidak perlu pengalaman khusus — cukup niat baik dan semangat berbagi.",
        "Konsumsi dan transport disediakan panitia. Kuota terbatas 60 relawan.",
      ],
      benefits: ["Sertifikat relawan YAKESMA", "Konsumsi & transport lokal", "Pengalaman & jejaring kebaikan"],
    },
    {
      slug: "kelas-parenting-islami-generasi-qurani",
      title: "Kelas Parenting Islami: Mendidik Generasi Qur'ani",
      category: "Kelas",
      speaker: "Bunda Rahma Firdausi, M.Psi.",
      location: "Online (Zoom)",
      city: "Online",
      online: true,
      date: "2026-09-13",
      timeStart: "09:00",
      timeEnd: "11:00",
      price: 50000,
      quota: 150,
      registered: 88,
      gradient: ["#f6b700", "#28a840"],
      emoji: "👨‍👩‍👧",
      excerpt: "Bekal mendidik anak dengan nilai Qur'ani sejak dini bagi para orang tua.",
      about: [
        "Kelas praktis bagi ayah dan bunda untuk menanamkan akhlak dan kecintaan pada Al-Qur'an sejak dini. Dibawakan oleh psikolog keluarga dengan pendekatan yang mudah diterapkan di rumah.",
        "Termasuk sesi tanya-jawab dan lembar aktivitas keluarga.",
      ],
      benefits: ["Sesi live 2 jam + rekaman", "E-book panduan parenting Qur'ani", "E-sertifikat peserta"],
    },
    {
      slug: "festival-anak-sholeh-bazar-umkm",
      title: "Festival Anak Sholeh & Bazar UMKM",
      category: "Sosial",
      speaker: "",
      location: "Lapangan Merdeka",
      city: "Depok",
      online: false,
      date: "2026-09-21",
      timeStart: "08:00",
      timeEnd: "16:00",
      price: 0,
      quota: 800,
      registered: 226,
      gradient: ["#f58634", "#185838"],
      emoji: "🎪",
      excerpt: "Lomba anak, dongeng islami, dan bazar UMKM binaan YAKESMA.",
      about: [
        "Festival keluarga yang menghadirkan lomba anak sholeh, panggung dongeng islami, dan bazar produk UMKM binaan YAKESMA. Gratis dan terbuka untuk umum.",
        "Ajak si kecil merasakan keseruan sambil mendukung UMKM mustahik naik kelas.",
      ],
      benefits: ["Akses seluruh area festival", "Ragam lomba & hadiah untuk anak", "Voucher belanja bazar"],
    },
    {
      slug: "program-wakaf-quran-santunan-guru-ngaji",
      title: "Program Wakaf Qur'an & Santunan Guru Ngaji",
      category: "Sosial",
      speaker: "",
      location: "Program Nasional",
      city: "Online",
      online: true,
      date: "2026-10-05",
      timeStart: "08:00",
      timeEnd: "selesai",
      price: 250000,
      quota: 500,
      registered: 132,
      gradient: ["#1f9036", "#f6b700"],
      emoji: "🌙",
      excerpt: "Wakafkan Al-Qur'an ke pelosok dan bantu kesejahteraan para guru ngaji.",
      about: [
        "Satu paket wakaf senilai Rp250.000 mencakup pengadaan mushaf Al-Qur'an untuk santri di pelosok serta santunan untuk para guru ngaji yang mengabdi tanpa lelah.",
        "Program berjalan sepanjang tahun. Anda akan menerima laporan penyaluran secara berkala.",
      ],
      benefits: ["Sertifikat wakaf atas nama Anda", "Laporan penyaluran berkala", "Doa dari para penerima manfaat"],
    },
  ],
};
